DB_NAME="database.db"
MAX_TENTATIVAS_LOGIN=3
LIMITE_SAQUE=2000.0

TIPO_DEPOSITO = "DEPOSITO"
TIPO_SAQUE = "SAQUE"
TIPO_TRANSFERENCIA_ENVIADA = "TRANSFERENCIA_ENVIADA"
TIPO_TRANSFERENCIA_RECEBIDA = "TRANSFERENCIA_RECEBIDA"
