[pytest]
testpaths = testes
python_files = teste_*.py
pythonpath = .

markers =
    slow: teste que demora para rodar
    db: teste que acessa o banco de dados
    security: teste relacionado a autenticacao/bcrypt
